// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct BinarySearch
{
  struct BinarySearch_vtable *vptr;
};
struct BS
{
  struct BS_vtable *vptr;
  int*  number;
  int size;
};
// vtables structures
struct BinarySearch_vtable
{
};

struct BS_vtable
{
  int (*Start)();
  int (*Search)();
  int (*Div)();
  int (*Compare)();
  int (*Print)();
  int (*Init)();
};


// vtables declared
struct BinarySearch_vtable BinarySearch_vtable_ ;
struct BS_vtable BS_vtable_ ;

// methods
int BS_Start(struct BS * this, int sz)
{
  int aux01;
  int aux02;
  struct BS * x_1;
  struct BS * x_2;
  struct BS * x_3;
  struct BS * x_4;
  struct BS * x_5;
  struct BS * x_6;
  struct BS * x_7;
  struct BS * x_8;
  struct BS * x_9;
  struct BS * x_10;
  int x_14;
  int x_15;
  int x_16;
  int x_17;
  int x_18;
  int x_19;
  int x_20;
  int x_21;
  int x_22;
  int x_23;

L_0:
  x_14 = this->vptr->Init(this, sz);
  aux01 = x_14;
  x_15 = this->vptr->Print(this);
  aux02 = x_15;
  x_16 = this->vptr->Search(this, 8);
  if (x_16)
    goto L_1;
  else
    goto L_2;
L_2:
  System_out_println (0);
  goto L_3;
L_1:
  System_out_println (1);
  goto L_3;
L_3:
  x_17 = this->vptr->Search(this, 19);
  if (x_17)
    goto L_4;
  else
    goto L_5;
L_5:
  System_out_println (0);
  goto L_6;
L_4:
  System_out_println (1);
  goto L_6;
L_6:
  x_18 = this->vptr->Search(this, 20);
  if (x_18)
    goto L_7;
  else
    goto L_8;
L_8:
  System_out_println (0);
  goto L_9;
L_7:
  System_out_println (1);
  goto L_9;
L_9:
  x_19 = this->vptr->Search(this, 21);
  if (x_19)
    goto L_10;
  else
    goto L_11;
L_11:
  System_out_println (0);
  goto L_12;
L_10:
  System_out_println (1);
  goto L_12;
L_12:
  x_20 = this->vptr->Search(this, 37);
  if (x_20)
    goto L_13;
  else
    goto L_14;
L_14:
  System_out_println (0);
  goto L_15;
L_13:
  System_out_println (1);
  goto L_15;
L_15:
  x_21 = this->vptr->Search(this, 38);
  if (x_21)
    goto L_16;
  else
    goto L_17;
L_17:
  System_out_println (0);
  goto L_18;
L_16:
  System_out_println (1);
  goto L_18;
L_18:
  x_22 = this->vptr->Search(this, 39);
  if (x_22)
    goto L_19;
  else
    goto L_20;
L_20:
  System_out_println (0);
  goto L_21;
L_19:
  System_out_println (1);
  goto L_21;
L_21:
  x_23 = this->vptr->Search(this, 50);
  if (x_23)
    goto L_22;
  else
    goto L_23;
L_23:
  System_out_println (0);
  goto L_24;
L_22:
  System_out_println (1);
  goto L_24;
L_24:
  return 999;
}
int BS_Search(struct BS * this, int num)
{
  int bs01;
  int right;
  int left;
  int var_cont;
  int medium;
  int aux01;
  int nt;
  struct BS * x_11;
  struct BS * x_12;
  struct BS * x_13;
  int x_24;
  int x_25;
  int x_26;
  int x_27;
  int x_28;
  int x_29;
  int x_30;
  int x_31;
  int x_32;
  int x_33;
  int x_34;

L_25:
  aux01 = 0;
  bs01 = 0;
  x_24 = Length(this->number);
  right = x_24;
  x_25 = right - 1;
  right = x_25;
  left = 0;
  var_cont = 1;
  goto L_26;
L_26:
  if (var_cont)
    goto L_27;
  else
    goto L_28;
L_27:
  x_26 = left + right;
  medium = x_26;
  x_27 = this->vptr->Div(this, medium);
  medium = x_27;
  x_28 = this->number[medium];
  aux01 = x_28;
  x_29 = num < aux01;
  if (x_29)
    goto L_29;
  else
    goto L_30;
L_30:
  x_30 = medium + 1;
  left = x_30;
  goto L_31;
L_29:
  x_31 = medium - 1;
  right = x_31;
  goto L_31;
L_31:
  x_32 = this->vptr->Compare(this, aux01, num);
  if (x_32)
    goto L_32;
  else
    goto L_33;
L_33:
  var_cont = 1;
  goto L_34;
L_32:
  var_cont = 0;
  goto L_34;
L_34:
  x_33 = right < left;
  if (x_33)
    goto L_35;
  else
    goto L_36;
L_36:
  nt = 0;
  goto L_37;
L_35:
  var_cont = 0;
  goto L_37;
L_37:

  goto L_26;
L_28:
  x_34 = this->vptr->Compare(this, aux01, num);
  if (x_34)
    goto L_38;
  else
    goto L_39;
L_39:
  bs01 = 0;
  goto L_40;
L_38:
  bs01 = 1;
  goto L_40;
L_40:
  return bs01;
}
int BS_Div(struct BS * this, int num)
{
  int count01;
  int count02;
  int aux03;
  int x_35;
  int x_36;
  int x_37;
  int x_38;

L_41:
  count01 = 0;
  count02 = 0;
  x_35 = num - 1;
  aux03 = x_35;
  goto L_42;
L_42:
  x_36 = count02 < aux03;
  if (x_36)
    goto L_43;
  else
    goto L_44;
L_43:
  x_37 = count01 + 1;
  count01 = x_37;
  x_38 = count02 + 2;
  count02 = x_38;

  goto L_42;
L_44:
  return count01;
}
int BS_Compare(struct BS * this, int num1, int num2)
{
  int retval;
  int aux02;
  int x_39;
  int x_40;
  int x_41;
  int x_42;

L_45:
  retval = 0;
  x_39 = num2 + 1;
  aux02 = x_39;
  x_40 = num1 < num2;
  if (x_40)
    goto L_46;
  else
    goto L_47;
L_47:
  x_42 = num1 < aux02;
  x_41 = !(x_42);
  if (x_41)
    goto L_49;
  else
    goto L_50;
L_50:
  retval = 1;
  goto L_51;
L_49:
  retval = 0;
  goto L_51;
L_51:
  goto L_48;
L_46:
  retval = 0;
  goto L_48;
L_48:
  return retval;
}
int BS_Print(struct BS * this)
{
  int j;
  int x_43;
  int x_44;
  int x_45;

L_52:
  j = 1;
  goto L_53;
L_53:
  x_43 = j < this->size;
  if (x_43)
    goto L_54;
  else
    goto L_55;
L_54:
  x_44 = this->number[j];
  System_out_println (x_44);
  x_45 = j + 1;
  j = x_45;

  goto L_53;
L_55:
  System_out_println (99999);
  return 0;
}
int BS_Init(struct BS * this, int sz)
{
  int j;
  int k;
  int aux02;
  int aux01;
  int*  x_46;
  int x_47;
  int x_48;
  int x_49;
  int x_50;
  int x_51;
  int x_52;
  int x_53;

L_56:
  this->size = sz;
  x_46 = (int *)Tiger_new_array(sz);
  this->number = x_46;
  j = 1;
  x_47 = this->size + 1;
  k = x_47;
  goto L_57;
L_57:
  x_48 = j < this->size;
  if (x_48)
    goto L_58;
  else
    goto L_59;
L_58:
  x_49 = 2 * j;
  aux01 = x_49;
  x_50 = k - 3;
  aux02 = x_50;
  x_51 = aux01 + aux02;
  this->number[j] = x_51;
  x_52 = j + 1;
  j = x_52;
  x_53 = k - 1;
  k = x_53;

  goto L_57;
L_59:
  return 0;
}

// vtables
struct BinarySearch_vtable BinarySearch_vtable_ = 
{
};

struct BS_vtable BS_vtable_ = 
{
  BS_Start,
  BS_Search,
  BS_Div,
  BS_Compare,
  BS_Print,
  BS_Init,
};


// main method
int Tiger_main ()
{
  struct BS * x_0;
  int x_54;
  struct BS * x_55;

L_60:
  x_55 = ((struct BS*)(Tiger_new (&BS_vtable_, sizeof(struct BS))));
  x_54 = x_55->vptr->Start(x_55, 20);
  System_out_println (x_54);
  return 0;
}




void *prev;
