; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public A
.super java/lang/Object

.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


