; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public BBS
.super java/lang/Object

.field public number [I
.field public size I
.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public Start(I)I
.limit stack 4096
.limit locals 4
    aload 0
    iload 1
    invokevirtual BBS/Init(I)I
    istore 2
    aload 0
    invokevirtual BBS/Print()I
    istore 2
    ldc 99999
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    aload 0
    invokevirtual BBS/Sort()I
    istore 2
    aload 0
    invokevirtual BBS/Print()I
    istore 2
    ldc 0
    ireturn
.end method
.method public Sort()I
.limit stack 4096
.limit locals 11
    aload 0
    getfield BBS/size I
    ldc 1
    isub
    istore 2
    ldc 0
    ldc 1
    isub
    istore 3
L_1:
    iload 3
    iload 2
    if_icmplt L_2
L_3:
    ldc 0
    goto L_4
L_2:
    ldc 1
L_4:
    ifeq L_0
    ldc 1
    istore 8
L_6:
    iload 8
    iload 2
    ldc 1
    iadd
    if_icmplt L_7
L_8:
    ldc 0
    goto L_9
L_7:
    ldc 1
L_9:
    ifeq L_5
    iload 8
    ldc 1
    isub
    istore 7
    aload 0
    getfield BBS/number [I
    iload 7
    iaload
    istore 4
    aload 0
    getfield BBS/number [I
    iload 8
    iaload
    istore 5
    iload 5
    iload 4
    if_icmplt L_12
L_13:
    ldc 0
    goto L_14
L_12:
    ldc 1
L_14:
    ifeq L_10
    iload 8
    ldc 1
    isub
    istore 6
    aload 0
    getfield BBS/number [I
    iload 6
    iaload
    istore 9
    aload 0
    getfield BBS/number [I
    iload 6
    aload 0
    getfield BBS/number [I
    iload 8
    iaload
    iastore
    aload 0
    getfield BBS/number [I
    iload 8
    iload 9
    iastore
    goto L_11
L_10:
    ldc 0
    istore 1
L_11:
    iload 8
    ldc 1
    iadd
    istore 8
    goto L_6
L_5:
    iload 2
    ldc 1
    isub
    istore 2
    goto L_1
L_0:
    ldc 0
    ireturn
.end method
.method public Print()I
.limit stack 4096
.limit locals 3
    ldc 0
    istore 1
L_16:
    iload 1
    aload 0
    getfield BBS/size I
    if_icmplt L_17
L_18:
    ldc 0
    goto L_19
L_17:
    ldc 1
L_19:
    ifeq L_15
    aload 0
    getfield BBS/number [I
    iload 1
    iaload
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    iload 1
    ldc 1
    iadd
    istore 1
    goto L_16
L_15:
    ldc 0
    ireturn
.end method
.method public Init(I)I
.limit stack 4096
.limit locals 3
    aload 0
    iload 1
    putfield BBS/size I
    aload 0
    iload 1
    newarray int
    putfield BBS/number [I
    aload 0
    getfield BBS/number [I
    ldc 0
    ldc 20
    iastore
    aload 0
    getfield BBS/number [I
    ldc 1
    ldc 7
    iastore
    aload 0
    getfield BBS/number [I
    ldc 2
    ldc 12
    iastore
    aload 0
    getfield BBS/number [I
    ldc 3
    ldc 18
    iastore
    aload 0
    getfield BBS/number [I
    ldc 4
    ldc 2
    iastore
    aload 0
    getfield BBS/number [I
    ldc 5
    ldc 11
    iastore
    aload 0
    getfield BBS/number [I
    ldc 6
    ldc 6
    iastore
    aload 0
    getfield BBS/number [I
    ldc 7
    ldc 9
    iastore
    aload 0
    getfield BBS/number [I
    ldc 8
    ldc 19
    iastore
    aload 0
    getfield BBS/number [I
    ldc 9
    ldc 5
    iastore
    ldc 0
    ireturn
.end method
