; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public BS
.super java/lang/Object

.field public number [I
.field public size I
.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public Start(I)I
.limit stack 4096
.limit locals 5
    aload 0
    iload 1
    invokevirtual BS/Init(I)I
    istore 2
    aload 0
    invokevirtual BS/Print()I
    istore 3
    aload 0
    ldc 8
    invokevirtual BS/Search(I)Z
    ifeq L_0
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_1
L_0:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_1:
    aload 0
    ldc 19
    invokevirtual BS/Search(I)Z
    ifeq L_2
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_3
L_2:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_3:
    aload 0
    ldc 20
    invokevirtual BS/Search(I)Z
    ifeq L_4
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_5
L_4:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_5:
    aload 0
    ldc 21
    invokevirtual BS/Search(I)Z
    ifeq L_6
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_7
L_6:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_7:
    aload 0
    ldc 37
    invokevirtual BS/Search(I)Z
    ifeq L_8
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_9
L_8:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_9:
    aload 0
    ldc 38
    invokevirtual BS/Search(I)Z
    ifeq L_10
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_11
L_10:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_11:
    aload 0
    ldc 39
    invokevirtual BS/Search(I)Z
    ifeq L_12
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_13
L_12:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_13:
    aload 0
    ldc 50
    invokevirtual BS/Search(I)Z
    ifeq L_14
    ldc 1
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    goto L_15
L_14:
    ldc 0
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
L_15:
    ldc 999
    ireturn
.end method
.method public Search(I)Z
.limit stack 4096
.limit locals 10
    ldc 0
    istore 7
    ldc 0
    istore 2
    aload 0
    getfield BS/number [I
    arraylength
    istore 3
    iload 3
    ldc 1
    isub
    istore 3
    ldc 0
    istore 4
    ldc 1
    istore 5
L_17:
    iload 5
    ifeq L_16
    iload 4
    iload 3
    iadd
    istore 6
    aload 0
    iload 6
    invokevirtual BS/Div(I)I
    istore 6
    aload 0
    getfield BS/number [I
    iload 6
    iaload
    istore 7
    iload 1
    iload 7
    if_icmplt L_20
L_21:
    ldc 0
    goto L_22
L_20:
    ldc 1
L_22:
    ifeq L_18
    iload 6
    ldc 1
    isub
    istore 3
    goto L_19
L_18:
    iload 6
    ldc 1
    iadd
    istore 4
L_19:
    aload 0
    iload 7
    iload 1
    invokevirtual BS/Compare(II)Z
    ifeq L_23
    ldc 0
    istore 5
    goto L_24
L_23:
    ldc 1
    istore 5
L_24:
    iload 3
    iload 4
    if_icmplt L_27
L_28:
    ldc 0
    goto L_29
L_27:
    ldc 1
L_29:
    ifeq L_25
    ldc 0
    istore 5
    goto L_26
L_25:
    ldc 0
    istore 8
L_26:
    goto L_17
L_16:
    aload 0
    iload 7
    iload 1
    invokevirtual BS/Compare(II)Z
    ifeq L_30
    ldc 1
    istore 2
    goto L_31
L_30:
    ldc 0
    istore 2
L_31:
    iload 2
    ireturn
.end method
.method public Div(I)I
.limit stack 4096
.limit locals 6
    ldc 0
    istore 2
    ldc 0
    istore 3
    iload 1
    ldc 1
    isub
    istore 4
L_33:
    iload 3
    iload 4
    if_icmplt L_34
L_35:
    ldc 0
    goto L_36
L_34:
    ldc 1
L_36:
    ifeq L_32
    iload 2
    ldc 1
    iadd
    istore 2
    iload 3
    ldc 2
    iadd
    istore 3
    goto L_33
L_32:
    iload 2
    ireturn
.end method
.method public Compare(II)Z
.limit stack 4096
.limit locals 6
    ldc 0
    istore 3
    iload 2
    ldc 1
    iadd
    istore 4
    iload 1
    iload 2
    if_icmplt L_39
L_40:
    ldc 0
    goto L_41
L_39:
    ldc 1
L_41:
    ifeq L_37
    ldc 0
    istore 3
    goto L_38
L_37:
    iload 1
    iload 4
    if_icmplt L_44
L_45:
    ldc 0
    goto L_46
L_44:
    ldc 1
L_46:
    ldc 1
    ixor
    ifeq L_42
    ldc 0
    istore 3
    goto L_43
L_42:
    ldc 1
    istore 3
L_43:
L_38:
    iload 3
    ireturn
.end method
.method public Print()I
.limit stack 4096
.limit locals 3
    ldc 1
    istore 1
L_48:
    iload 1
    aload 0
    getfield BS/size I
    if_icmplt L_49
L_50:
    ldc 0
    goto L_51
L_49:
    ldc 1
L_51:
    ifeq L_47
    aload 0
    getfield BS/number [I
    iload 1
    iaload
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    iload 1
    ldc 1
    iadd
    istore 1
    goto L_48
L_47:
    ldc 99999
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    ldc 0
    ireturn
.end method
.method public Init(I)I
.limit stack 4096
.limit locals 7
    aload 0
    iload 1
    putfield BS/size I
    aload 0
    iload 1
    newarray int
    putfield BS/number [I
    ldc 1
    istore 2
    aload 0
    getfield BS/size I
    ldc 1
    iadd
    istore 3
L_53:
    iload 2
    aload 0
    getfield BS/size I
    if_icmplt L_54
L_55:
    ldc 0
    goto L_56
L_54:
    ldc 1
L_56:
    ifeq L_52
    ldc 2
    iload 2
    imul
    istore 5
    iload 3
    ldc 3
    isub
    istore 4
    aload 0
    getfield BS/number [I
    iload 2
    iload 5
    iload 4
    iadd
    iastore
    iload 2
    ldc 1
    iadd
    istore 2
    iload 3
    ldc 1
    isub
    istore 3
    goto L_53
L_52:
    ldc 0
    ireturn
.end method
