; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public Doit
.super java/lang/Object

.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public doit(I)I
.limit stack 4096
.limit locals 5
    iload 2
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    ldc 10
    istore 2
    ldc 20
    istore 2
    ldc 10
    istore 1
    ldc 0
    istore 3
    ldc 0
    istore 2
L_1:
    iload 3
    iload 1
    if_icmplt L_2
L_3:
    ldc 0
    goto L_4
L_2:
    ldc 1
L_4:
    ifeq L_0
    iload 2
    iload 3
    iadd
    istore 2
    iload 3
    ldc 1
    iadd
    istore 3
    goto L_1
L_0:
    iload 2
    ireturn
.end method
