; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public Element
.super java/lang/Object

.field public Age I
.field public Salary I
.field public Married Z
.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public Init(IIZ)Z
.limit stack 4096
.limit locals 5
    aload 0
    iload 1
    putfield Element/Age I
    aload 0
    iload 2
    putfield Element/Salary I
    aload 0
    iload 3
    putfield Element/Married Z
    ldc 1
    ireturn
.end method
.method public GetAge()I
.limit stack 4096
.limit locals 2
    aload 0
    getfield Element/Age I
    ireturn
.end method
.method public GetSalary()I
.limit stack 4096
.limit locals 2
    aload 0
    getfield Element/Salary I
    ireturn
.end method
.method public GetMarried()Z
.limit stack 4096
.limit locals 2
    aload 0
    getfield Element/Married Z
    ireturn
.end method
.method public Equal(LElement;)Z
.limit stack 4096
.limit locals 7
    ldc 1
    istore 2
    aload 1
    invokevirtual Element/GetAge()I
    istore 3
    aload 0
    iload 3
    aload 0
    getfield Element/Age I
    invokevirtual Element/Compare(II)Z
    ldc 1
    ixor
    ifeq L_0
    ldc 0
    istore 2
    goto L_1
L_0:
    aload 1
    invokevirtual Element/GetSalary()I
    istore 4
    aload 0
    iload 4
    aload 0
    getfield Element/Salary I
    invokevirtual Element/Compare(II)Z
    ldc 1
    ixor
    ifeq L_2
    ldc 0
    istore 2
    goto L_3
L_2:
    aload 0
    getfield Element/Married Z
    ifeq L_4
    aload 1
    invokevirtual Element/GetMarried()Z
    ldc 1
    ixor
    ifeq L_6
    ldc 0
    istore 2
    goto L_7
L_6:
    ldc 0
    istore 5
L_7:
    goto L_5
L_4:
    aload 1
    invokevirtual Element/GetMarried()Z
    ifeq L_8
    ldc 0
    istore 2
    goto L_9
L_8:
    ldc 0
    istore 5
L_9:
L_5:
L_3:
L_1:
    iload 2
    ireturn
.end method
.method public Compare(II)Z
.limit stack 4096
.limit locals 6
    ldc 0
    istore 3
    iload 2
    ldc 1
    iadd
    istore 4
    iload 1
    iload 2
    if_icmplt L_12
L_13:
    ldc 0
    goto L_14
L_12:
    ldc 1
L_14:
    ifeq L_10
    ldc 0
    istore 3
    goto L_11
L_10:
    iload 1
    iload 4
    if_icmplt L_17
L_18:
    ldc 0
    goto L_19
L_17:
    ldc 1
L_19:
    ldc 1
    ixor
    ifeq L_15
    ldc 0
    istore 3
    goto L_16
L_15:
    ldc 1
    istore 3
L_16:
L_11:
    iload 3
    ireturn
.end method
