; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public QS
.super java/lang/Object

.field public number [I
.field public size I
.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public Start(I)I
.limit stack 4096
.limit locals 4
    aload 0
    iload 1
    invokevirtual QS/Init(I)I
    istore 2
    aload 0
    invokevirtual QS/Print()I
    istore 2
    ldc 9999
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    aload 0
    getfield QS/size I
    ldc 1
    isub
    istore 2
    aload 0
    ldc 0
    iload 2
    invokevirtual QS/Sort(II)I
    istore 2
    aload 0
    invokevirtual QS/Print()I
    istore 2
    ldc 0
    ireturn
.end method
.method public Sort(II)I
.limit stack 4096
.limit locals 12
    ldc 0
    istore 7
    iload 1
    iload 2
    if_icmplt L_2
L_3:
    ldc 0
    goto L_4
L_2:
    ldc 1
L_4:
    ifeq L_0
    aload 0
    getfield QS/number [I
    iload 2
    iaload
    istore 3
    iload 1
    ldc 1
    isub
    istore 4
    iload 2
    istore 5
    ldc 1
    istore 8
L_6:
    iload 8
    ifeq L_5
    ldc 1
    istore 9
L_8:
    iload 9
    ifeq L_7
    iload 4
    ldc 1
    iadd
    istore 4
    aload 0
    getfield QS/number [I
    iload 4
    iaload
    istore 10
    iload 10
    iload 3
    if_icmplt L_11
L_12:
    ldc 0
    goto L_13
L_11:
    ldc 1
L_13:
    ldc 1
    ixor
    ifeq L_9
    ldc 0
    istore 9
    goto L_10
L_9:
    ldc 1
    istore 9
L_10:
    goto L_8
L_7:
    ldc 1
    istore 9
L_15:
    iload 9
    ifeq L_14
    iload 5
    ldc 1
    isub
    istore 5
    aload 0
    getfield QS/number [I
    iload 5
    iaload
    istore 10
    iload 3
    iload 10
    if_icmplt L_18
L_19:
    ldc 0
    goto L_20
L_18:
    ldc 1
L_20:
    ldc 1
    ixor
    ifeq L_16
    ldc 0
    istore 9
    goto L_17
L_16:
    ldc 1
    istore 9
L_17:
    goto L_15
L_14:
    aload 0
    getfield QS/number [I
    iload 4
    iaload
    istore 7
    aload 0
    getfield QS/number [I
    iload 4
    aload 0
    getfield QS/number [I
    iload 5
    iaload
    iastore
    aload 0
    getfield QS/number [I
    iload 5
    iload 7
    iastore
    iload 5
    iload 4
    ldc 1
    iadd
    if_icmplt L_23
L_24:
    ldc 0
    goto L_25
L_23:
    ldc 1
L_25:
    ifeq L_21
    ldc 0
    istore 8
    goto L_22
L_21:
    ldc 1
    istore 8
L_22:
    goto L_6
L_5:
    aload 0
    getfield QS/number [I
    iload 5
    aload 0
    getfield QS/number [I
    iload 4
    iaload
    iastore
    aload 0
    getfield QS/number [I
    iload 4
    aload 0
    getfield QS/number [I
    iload 2
    iaload
    iastore
    aload 0
    getfield QS/number [I
    iload 2
    iload 7
    iastore
    aload 0
    iload 1
    iload 4
    ldc 1
    isub
    invokevirtual QS/Sort(II)I
    istore 6
    aload 0
    iload 4
    ldc 1
    iadd
    iload 2
    invokevirtual QS/Sort(II)I
    istore 6
    goto L_1
L_0:
    ldc 0
    istore 6
L_1:
    ldc 0
    ireturn
.end method
.method public Print()I
.limit stack 4096
.limit locals 3
    ldc 0
    istore 1
L_27:
    iload 1
    aload 0
    getfield QS/size I
    if_icmplt L_28
L_29:
    ldc 0
    goto L_30
L_28:
    ldc 1
L_30:
    ifeq L_26
    aload 0
    getfield QS/number [I
    iload 1
    iaload
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    iload 1
    ldc 1
    iadd
    istore 1
    goto L_27
L_26:
    ldc 0
    ireturn
.end method
.method public Init(I)I
.limit stack 4096
.limit locals 3
    aload 0
    iload 1
    putfield QS/size I
    aload 0
    iload 1
    newarray int
    putfield QS/number [I
    aload 0
    getfield QS/number [I
    ldc 0
    ldc 20
    iastore
    aload 0
    getfield QS/number [I
    ldc 1
    ldc 7
    iastore
    aload 0
    getfield QS/number [I
    ldc 2
    ldc 12
    iastore
    aload 0
    getfield QS/number [I
    ldc 3
    ldc 18
    iastore
    aload 0
    getfield QS/number [I
    ldc 4
    ldc 2
    iastore
    aload 0
    getfield QS/number [I
    ldc 5
    ldc 11
    iastore
    aload 0
    getfield QS/number [I
    ldc 6
    ldc 6
    iastore
    aload 0
    getfield QS/number [I
    ldc 7
    ldc 9
    iastore
    aload 0
    getfield QS/number [I
    ldc 8
    ldc 19
    iastore
    aload 0
    getfield QS/number [I
    ldc 9
    ldc 5
    iastore
    ldc 0
    ireturn
.end method
