; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public TestFor
.super java/lang/Object

.method public static main([Ljava/lang/String;)V
    .limit stack 4096
    .limit locals 2
    new Test
    dup
    invokespecial Test/<init>()V
    ldc 20
    invokevirtual Test/doit(I)I
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    return
.end method
