; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public Visitor
.super java/lang/Object

.field public l LTree;
.field public r LTree;
.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public visit(LTree;)I
.limit stack 4096
.limit locals 4
    aload 1
    invokevirtual Tree/GetHas_Right()Z
    ifeq L_71
    aload 0
    aload 1
    invokevirtual Tree/GetRight()LTree;
    putfield Visitor/r LTree;
    aload 0
    getfield Visitor/r LTree;
    aload 0
    invokevirtual Tree/accept(LVisitor;)I
    istore 2
    goto L_72
L_71:
    ldc 0
    istore 2
L_72:
    aload 1
    invokevirtual Tree/GetHas_Left()Z
    ifeq L_73
    aload 0
    aload 1
    invokevirtual Tree/GetLeft()LTree;
    putfield Visitor/l LTree;
    aload 0
    getfield Visitor/l LTree;
    aload 0
    invokevirtual Tree/accept(LVisitor;)I
    istore 2
    goto L_74
L_73:
    ldc 0
    istore 2
L_74:
    ldc 0
    ireturn
.end method
