// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#define NULL ((void*)0)

// structures
struct BubbleSort
{
  struct BubbleSort_vtable *vptr;
};
struct BBS
{
  struct BBS_vtable *vptr;
  int*   number;
  int size;
};

// vtables structures
struct BubbleSort_vtable
{
  char *BubbleSort_gc_map;
};

struct BBS_vtable
{
  char *BBS_gc_map;
  int (*Start)();
  int (*Sort)();
  int (*Print)();
  int (*Init)();
};


// vtables declared
struct BubbleSort_vtable BubbleSort_vtable_ ;
struct BBS_vtable BBS_vtable_ ;

// methods
struct BBS_Start_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
  struct BBS * x_1;
  struct BBS * x_2;
  struct BBS * x_3;
  struct BBS * x_4;
};
char *BBS_Start_arguments_gc_map="10";
char *BBS_Start_locals_gc_map="01111";
void *prev;
int BBS_Start(struct BBS * this, int sz)
{
  struct BBS_Start_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = BBS_Start_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 4;
  int aux01;

  aux01 = (frame.x_1=this, frame.x_1->vptr->Init(frame.x_1, sz));
  aux01 = (frame.x_2=this, frame.x_2->vptr->Print(frame.x_2));
  System_out_println (99999);
  aux01 = (frame.x_3=this, frame.x_3->vptr->Sort(frame.x_3));
  aux01 = (frame.x_4=this, frame.x_4->vptr->Print(frame.x_4));
  return 0;
}

struct BBS_Sort_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
};
char *BBS_Sort_arguments_gc_map="1";
char *BBS_Sort_locals_gc_map="000000000";
void *prev;
int BBS_Sort(struct BBS * this)
{
  struct BBS_Sort_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = BBS_Sort_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 0;
  int nt;
  int i;
  int aux02;
  int aux04;
  int aux05;
  int aux06;
  int aux07;
  int j;
  int t;

  i = this->size - 1;
  aux02 = 0 - 1;
  while (aux02 < i)
  {
    j = 1;
    while (j < i+1)
    {
      aux07 = j - 1;
      aux04 = this->number[aux07];
      aux05 = this->number[j];
      if (aux05 < aux04){
        aux06 = j - 1;
        t = this->number[aux06];
        this->number[aux06] = this->number[j];
        this->number[j] = t;

      }else{
        nt = 0;
      }
      j = j+1;
    }
    i = i - 1;
  }
  return 0;
}

struct BBS_Print_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
};
char *BBS_Print_arguments_gc_map="1";
char *BBS_Print_locals_gc_map="0";
void *prev;
int BBS_Print(struct BBS * this)
{
  struct BBS_Print_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = BBS_Print_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 0;
  int j;

  j = 0;
  while (j < this->size)
  {
    System_out_println (this->number[j]);
    j = j+1;
  }
  return 0;
}

struct BBS_Init_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
};
char *BBS_Init_arguments_gc_map="10";
char *BBS_Init_locals_gc_map="";
void *prev;
int BBS_Init(struct BBS * this, int sz)
{
  struct BBS_Init_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = BBS_Init_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 0;

  this->size = sz;
  this->number = (int*)Tiger_new_array(sz);
  this->number[0] = 20;
  this->number[1] = 7;
  this->number[2] = 12;
  this->number[3] = 18;
  this->number[4] = 2;
  this->number[5] = 11;
  this->number[6] = 6;
  this->number[7] = 9;
  this->number[8] = 19;
  this->number[9] = 5;
  return 0;
}


// vtables
struct BubbleSort_vtable BubbleSort_vtable_ = 
{
  NULL,
};

struct BBS_vtable BBS_vtable_ = 
{
  "10",
  BBS_Start,
  BBS_Sort,
  BBS_Print,
  BBS_Init,
};


// main method
struct main_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
  struct BBS * x_0;
};
void *prev;
int Tiger_main ()
{
  struct  main_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = NULL;
  frame.arguments_base_address = 0;
  frame.locals_gc_map = 1;
  System_out_println ((frame.x_0=((struct BBS*)(Tiger_new (&BBS_vtable_, sizeof(struct BBS)))), frame.x_0->vptr->Start(frame.x_0, 10)));
}




