// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#define NULL ((void*)0)

#include <string.h>
// structures
struct DeadClass
{
  struct DeadClass_vtable *vptr;
  int isObjOrArray;
  int length;
  void *forwarding;
};

// vtables structures
struct DeadClass_vtable
{
  char *DeadClass_gc_map;
};


// vtables declared
struct DeadClass_vtable DeadClass_vtable_ ;

// methods

// vtables
struct DeadClass_vtable DeadClass_vtable_ = 
{
  "",
};


// main method
struct main_gc_frame{
  void *prev;
  char *arguments_gc_map;
  void *arguments_base_address;
  int locals_gc_map;
};
void *prev;
int Tiger_main ()
{
  struct  main_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = NULL;
  frame.arguments_base_address = 0;
  frame.locals_gc_map = 0;

  System_out_println (10);

  prev=frame.prev;
}




