// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#define NULL ((void*)0)

#include <string.h>
// structures
struct Factorial
{
  struct Factorial_vtable *vptr;
  int isObjOrArray;
  int length;
  void *forwarding;
};
struct Fac
{
  struct Fac_vtable *vptr;
  int isObjOrArray;
  int length;
  void *forwarding;
};

// vtables structures
struct Factorial_vtable
{
  char *Factorial_gc_map;
};

struct Fac_vtable
{
  char *Fac_gc_map;
  int (*ComputeFac)();
};


// vtables declared
struct Factorial_vtable Factorial_vtable_ ;
struct Fac_vtable Fac_vtable_ ;

// methods
struct Fac_ComputeFac_gc_frame{
  void *prev;
  char *arguments_gc_map;
  void *arguments_base_address;
  int locals_gc_map;
  struct Fac * x_1;
};
char *Fac_ComputeFac_arguments_gc_map="10";
char *Fac_ComputeFac_locals_gc_map="01";
void *prev;
int Fac_ComputeFac(struct Fac * this, int num)
{
  struct Fac_ComputeFac_gc_frame frame;

  memset(&frame,0,sizeof(frame));
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Fac_ComputeFac_arguments_gc_map;
  frame.arguments_base_address =&this;
  frame.locals_gc_map = 1;

  int num_aux;

  if (num < 1){
    num_aux = 1;

  }else{
    num_aux = num * (frame.x_1=this, frame.x_1->vptr->ComputeFac(frame.x_1, num - 1));
  }
  prev=frame.prev;
  return num_aux;
}


// vtables
struct Factorial_vtable Factorial_vtable_ = 
{
  "",
};

struct Fac_vtable Fac_vtable_ = 
{
  "",
  Fac_ComputeFac,
};


// main method
struct main_gc_frame{
  void *prev;
  char *arguments_gc_map;
  void *arguments_base_address;
  int locals_gc_map;
  struct Fac * x_0;
};
void *prev;
int Tiger_main ()
{
  struct  main_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = NULL;
  frame.arguments_base_address = 0;
  frame.locals_gc_map = 1;

  System_out_println ((frame.x_0=((struct Fac*)(Tiger_new (&Fac_vtable_, sizeof(struct Fac)))), frame.x_0->vptr->ComputeFac(frame.x_0, 10)));

  prev=frame.prev;
}




