// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#define NULL ((void*)0)

// structures
struct Factorial
{
  struct Factorial_vtable *vptr;
};
struct Fac
{
  struct Fac_vtable *vptr;
};

// vtables structures
struct Factorial_vtable
{
  char *Factorial_gc_map;
};

struct Fac_vtable
{
  char *Fac_gc_map;
  int (*ComputeFac)();
};


// vtables declared
struct Factorial_vtable Factorial_vtable_ ;
struct Fac_vtable Fac_vtable_ ;

// methods
struct Fac_ComputeFac_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
  struct Fac * x_1;
};
char *Fac_ComputeFac_arguments_gc_map="10";
char *Fac_ComputeFac_locals_gc_map="01";
void *prev;
int Fac_ComputeFac(struct Fac * this, int num)
{
  struct Fac_ComputeFac_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Fac_ComputeFac_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 1;
  int num_aux;
  struct Fac * x_1;
  frame.x_1 = x_1;

  if (num < 1){
    num_aux = 1;

  }else{
    num_aux = num * (x_1=this, x_1->vptr->ComputeFac(x_1, num - 1));
  }
  return num_aux;
}


// vtables
struct Factorial_vtable Factorial_vtable_ = 
{
  NULL,
};

struct Fac_vtable Fac_vtable_ = 
{
  NULL,
  Fac_ComputeFac,
};


// main method
int Tiger_main ()
{
  struct Fac * x_0;
  System_out_println ((x_0=((struct Fac*)(Tiger_new (&Fac_vtable_, sizeof(struct Fac)))), x_0->vptr->ComputeFac(x_0, 10)));
}




