// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct LinearSearch
{
  struct LinearSearch_vtable *vptr;
};
struct LS
{
  struct LS_vtable *vptr;
  int*   number;
  int size;
};

// vtables structures
struct LinearSearch_vtable
{
};

struct LS_vtable
{
  int (*Start)();
  int (*Print)();
  int (*Search)();
  int (*Init)();
};


// vtables declared
struct LinearSearch_vtable LinearSearch_vtable_ ;
struct LS_vtable LS_vtable_ ;

// methods
int LS_Start(struct LS * this, int sz)
{
  int aux01;
  int aux02;
  struct LS * x_1;
  struct LS * x_2;
  struct LS * x_3;
  struct LS * x_4;
  struct LS * x_5;
  struct LS * x_6;

  aux01 = (x_1=this, x_1->vptr->Init(x_1, sz));
  aux02 = (x_2=this, x_2->vptr->Print(x_2));
  System_out_println (9999);
  System_out_println ((x_3=this, x_3->vptr->Search(x_3, 8)));
  System_out_println ((x_4=this, x_4->vptr->Search(x_4, 12)));
  System_out_println ((x_5=this, x_5->vptr->Search(x_5, 17)));
  System_out_println ((x_6=this, x_6->vptr->Search(x_6, 50)));
  return 55;
}
int LS_Print(struct LS * this)
{
  int j;

  j = 1;
  while (j < this->size)
  {
    System_out_println (this->number[j]);
    j = j+1;
  }
  return 0;
}
int LS_Search(struct LS * this, int num)
{
  int j;
  int ls01;
  int ifound;
  int aux01;
  int aux02;
  int nt;

  j = 1;
  ls01 = 0;
  ifound = 0;
  while (j < this->size)
  {
    aux01 = this->number[j];
    aux02 = num+1;
    if (aux01 < num){
      nt = 0;

    }else{
      if (!(aux01 < aux02)){
        nt = 0;

      }else{
        ls01 = 1;
        ifound = 1;
        j = this->size;
      }
    }
    j = j+1;
  }
  return ifound;
}
int LS_Init(struct LS * this, int sz)
{
  int j;
  int k;
  int aux01;
  int aux02;

  this->size = sz;
  this->number = (int*)Array_new(sz);
  j = 1;
  k = this->size+1;
  while (j < this->size)
  {
    aux01 = 2 * j;
    aux02 = k - 3;
    this->number[j] = aux01+aux02;
    j = j+1;
    k = k - 1;
  }
  return 0;
}

// vtables
struct LinearSearch_vtable LinearSearch_vtable_ = 
{
};

struct LS_vtable LS_vtable_ = 
{
  LS_Start,
  LS_Print,
  LS_Search,
  LS_Init,
};


// main method
int Tiger_main ()
{
  struct LS * x_0;
  System_out_println ((x_0=((struct LS*)(Tiger_new (&LS_vtable_, sizeof(struct LS)))), x_0->vptr->Start(x_0, 10)));
}




