// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#define NULL ((void*)0)

// structures
struct LinearSearch
{
  struct LinearSearch_vtable *vptr;
};
struct LS
{
  struct LS_vtable *vptr;
  int*   number;
  int size;
};

// vtables structures
struct LinearSearch_vtable
{
  char *LinearSearch_gc_map;
};

struct LS_vtable
{
  char *LS_gc_map;
  int (*Start)();
  int (*Print)();
  int (*Search)();
  int (*Init)();
};


// vtables declared
struct LinearSearch_vtable LinearSearch_vtable_ ;
struct LS_vtable LS_vtable_ ;

// methods
struct LS_Start_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
  struct LS * x_1;
  struct LS * x_2;
  struct LS * x_3;
  struct LS * x_4;
  struct LS * x_5;
  struct LS * x_6;
};
char *LS_Start_arguments_gc_map="10";
char *LS_Start_locals_gc_map="00111111";
void *prev;
int LS_Start(struct LS * this, int sz)
{
  struct LS_Start_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = LS_Start_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 6;
  int aux01;
  int aux02;
  struct LS * x_1;
  frame.x_1 = x_1;
  struct LS * x_2;
  frame.x_2 = x_2;
  struct LS * x_3;
  frame.x_3 = x_3;
  struct LS * x_4;
  frame.x_4 = x_4;
  struct LS * x_5;
  frame.x_5 = x_5;
  struct LS * x_6;
  frame.x_6 = x_6;

  aux01 = (x_1=this, x_1->vptr->Init(x_1, sz));
  aux02 = (x_2=this, x_2->vptr->Print(x_2));
  System_out_println (9999);
  System_out_println ((x_3=this, x_3->vptr->Search(x_3, 8)));
  System_out_println ((x_4=this, x_4->vptr->Search(x_4, 12)));
  System_out_println ((x_5=this, x_5->vptr->Search(x_5, 17)));
  System_out_println ((x_6=this, x_6->vptr->Search(x_6, 50)));
  return 55;
}

struct LS_Print_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
};
char *LS_Print_arguments_gc_map="1";
char *LS_Print_locals_gc_map="0";
void *prev;
int LS_Print(struct LS * this)
{
  struct LS_Print_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = LS_Print_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 0;
  int j;

  j = 1;
  while (j < this->size)
  {
    System_out_println (this->number[j]);
    j = j+1;
  }
  return 0;
}

struct LS_Search_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
};
char *LS_Search_arguments_gc_map="10";
char *LS_Search_locals_gc_map="000000";
void *prev;
int LS_Search(struct LS * this, int num)
{
  struct LS_Search_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = LS_Search_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 0;
  int j;
  int ls01;
  int ifound;
  int aux01;
  int aux02;
  int nt;

  j = 1;
  ls01 = 0;
  ifound = 0;
  while (j < this->size)
  {
    aux01 = this->number[j];
    aux02 = num+1;
    if (aux01 < num){
      nt = 0;

    }else{
      if (!(aux01 < aux02)){
        nt = 0;

      }else{
        ls01 = 1;
        ifound = 1;
        j = this->size;
      }
    }
    j = j+1;
  }
  return ifound;
}

struct LS_Init_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_map;
};
char *LS_Init_arguments_gc_map="10";
char *LS_Init_locals_gc_map="0000";
void *prev;
int LS_Init(struct LS * this, int sz)
{
  struct LS_Init_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = LS_Init_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 0;
  int j;
  int k;
  int aux01;
  int aux02;

  this->size = sz;
  this->number = (int*)Tiger_new_array(sz);
  j = 1;
  k = this->size+1;
  while (j < this->size)
  {
    aux01 = 2 * j;
    aux02 = k - 3;
    this->number[j] = aux01+aux02;
    j = j+1;
    k = k - 1;
  }
  return 0;
}


// vtables
struct LinearSearch_vtable LinearSearch_vtable_ = 
{
  NULL,
};

struct LS_vtable LS_vtable_ = 
{
  "10",
  LS_Start,
  LS_Print,
  LS_Search,
  LS_Init,
};


// main method
int Tiger_main ()
{
  struct LS * x_0;
  System_out_println ((x_0=((struct LS*)(Tiger_new (&LS_vtable_, sizeof(struct LS)))), x_0->vptr->Start(x_0, 10)));
}




