// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct MyTest
{
  struct MyTest_vtable *vptr;
};
struct B
{
  struct B_vtable *vptr;
};

// vtables structures
struct MyTest_vtable
{
};

struct B_vtable
{
  int (*bar)();
};


// vtables declared
struct MyTest_vtable MyTest_vtable_ ;
struct B_vtable B_vtable_ ;

// methods
int B_bar(struct B * this)
{
  b = ((struct B*)(Tiger_new (&B_vtable_, sizeof(struct B))));
  return 1;
}


// vtables
struct MyTest_vtable MyTest_vtable_ = 
{
};

struct B_vtable B_vtable_ = 
{
  B_bar,
};


// main method
int Tiger_main ()
{
  System_out_println (20);
}




