// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#define NULL ((void*)0)

// structures
struct Sum
{
  struct Sum_vtable *vptr;
};
struct Doit
{
  struct Doit_vtable *vptr;
};

// vtables structures
struct Sum_vtable
{
  char *Sum_gc_map;
};

struct Doit_vtable
{
  char *Doit_gc_map;
  int (*doit)();
};


// vtables declared
struct Sum_vtable Sum_vtable_ ;
struct Doit_vtable Doit_vtable_ ;

// methods
struct Doit_doit_gc_frame{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  char *locals_gc_map;
};
char *Doit_doit_arguments_gc_map="10";
char *Doit_doit_locals_gc_map="00";
void *prev;
int Doit_doit(struct Doit * this, int n)
{
  struct Doit_doit_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Doit_doit_arguments_gc_map;
  frame.arguments_base_address =(int*) &this;
  frame.locals_gc_map = 0;
  int sum;
  int i;

  i = 0;
  sum = 0;
  while (i < n)
  {
    sum = sum+i;
    i = i+1;
  }
  return sum;
}


// vtables
struct Sum_vtable Sum_vtable_ = 
{
  NULL,
};

struct Doit_vtable Doit_vtable_ = 
{
  NULL,
  Doit_doit,
};


// main method
int Tiger_main ()
{
  struct Doit * x_0;
  System_out_println ((x_0=((struct Doit*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit)))), x_0->vptr->doit(x_0, 20)));
}




