// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#define NULL ((void*)0)

#include <string.h>
// structures
struct TestFor
{
  struct TestFor_vtable *vptr;
  int isObjOrArray;
  int length;
  void *forwarding;
};
struct Test
{
  struct Test_vtable *vptr;
  int isObjOrArray;
  int length;
  void *forwarding;
};

// vtables structures
struct TestFor_vtable
{
  char *TestFor_gc_map;
};

struct Test_vtable
{
  char *Test_gc_map;
  int (*doit)();
};


// vtables declared
struct TestFor_vtable TestFor_vtable_ ;
struct Test_vtable Test_vtable_ ;

// methods
struct Test_doit_gc_frame{
  void *prev;
  char *arguments_gc_map;
  void *arguments_base_address;
  int locals_gc_map;
};
char *Test_doit_arguments_gc_map="10";
char *Test_doit_locals_gc_map="00";
void *prev;
int Test_doit(struct Test * this, int n)
{
  struct Test_doit_gc_frame frame;

  memset(&frame,0,sizeof(frame));
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Test_doit_arguments_gc_map;
  frame.arguments_base_address =&this;
  frame.locals_gc_map = 0;

  int sum;
  int i;

  i = 0;
  i = i+1;
  System_out_println (i);
  i = i - 1;
  System_out_println (i);
  i = i+1;
  i = i+1;
  sum = i;
  i = i+1;
  System_out_println (i);
  System_out_println (sum);
  sum = 0;
  while (i < n)
  {
    sum = sum+i;
    i = i+1;
  }
  prev=frame.prev;
  return sum;
}


// vtables
struct TestFor_vtable TestFor_vtable_ = 
{
  "",
};

struct Test_vtable Test_vtable_ = 
{
  "",
  Test_doit,
};


// main method
struct main_gc_frame{
  void *prev;
  char *arguments_gc_map;
  void *arguments_base_address;
  int locals_gc_map;
  struct Test * x_0;
};
void *prev;
int Tiger_main ()
{
  struct  main_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = NULL;
  frame.arguments_base_address = 0;
  frame.locals_gc_map = 1;

  System_out_println ((frame.x_0=((struct Test*)(Tiger_new (&Test_vtable_, sizeof(struct Test)))), frame.x_0->vptr->doit(frame.x_0, 20)));

  prev=frame.prev;
}




