; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public BinarySearch
.super java/lang/Object

.method public static main([Ljava/lang/String;)V
    .limit stack 4096
    .limit locals 2
    new BS
    dup
    invokespecial BS/<init>()V
    ldc 20
    invokevirtual BS/Start(I)I
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    return
.end method
