; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public MyVisitor
.super Visitor
.method public <init>()V
    aload 0
    invokespecial Visitor/<init>()V
    return
.end method


.method public visit(LTree;)I
.limit stack 4096
.limit locals 4
    aload 1
    invokevirtual Tree/GetHas_Right()Z
    ifeq L_75
    aload 0
    aload 1
    invokevirtual Tree/GetRight()LTree;
    putfield MyVisitor/r LTree;
    aload 0
    getfield MyVisitor/r LTree;
    aload 0
    invokevirtual Tree/accept(LVisitor;)I
    istore 2
    goto L_76
L_75:
    ldc 0
    istore 2
L_76:
    aload 1
    invokevirtual Tree/GetKey()I
    getstatic java/lang/System/out Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(I)V
    aload 1
    invokevirtual Tree/GetHas_Left()Z
    ifeq L_77
    aload 0
    aload 1
    invokevirtual Tree/GetLeft()LTree;
    putfield MyVisitor/l LTree;
    aload 0
    getfield MyVisitor/l LTree;
    aload 0
    invokevirtual Tree/accept(LVisitor;)I
    istore 2
    goto L_78
L_77:
    ldc 0
    istore 2
L_78:
    ldc 0
    ireturn
.end method
